// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    repositories {
       maven {
           //允许使用外部库
           allowInsecureProtocol = true
           //阿里云镜像
           url "http://maven.aliyun.com/nexus/content/groups/public"
       }
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        // 修改
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0'
        // 修改
        classpath "com.android.tools.build:gradle:7.2.0"
//        classpath 'com.android.tools.build:gradle:8.6'
    }
}

allprojects {

    repositories {
        maven {
            //允许使用外部库
            allowInsecureProtocol = true
            //阿里云镜像
            url "http://maven.aliyun.com/nexus/content/groups/public"
        }
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

apply from: "$rootDir/buildResp/config.gradle"